[option]

[textrules]
style_direcitves = true
style_semicolon = true

[syntaxrules]
blocking_assignment_in_always_at_edge = true
case_default = true
default_nettype_none = true

# https://github.com/dalance/svlint/blob/master/MANUAL.md#configuration
